version: '2'

services:
  cassandra:
    extends:
      file: all.template
      service: cassandra
    expose:
      - "9042"

  zookeeper:
    extends:
      file: all.template
      service: zookeeper
    expose:
      - "2181"

  kafka:
    extends:
      file: all.template
      service: kafka
    expose:
      - "9092"
    extra_hosts:
      - "kafka:127.0.0.1"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      # 30 partitions, one replica; documentation is at
      # https://github.com/wurstmeister/kafka-docker#automatically-create-topics
      KAFKA_CREATE_TOPICS: "images:30:1"
    links:
      - zookeeper

  load:
    extends:
      file: all.template
      service: load
    environment:
      CASSANDRA_CONTACT_POINTS: cassandra
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    links:
      - cassandra
      - kafka
